### PR TITLE
Updated installation process.

### PR DESCRIPTION
**Pull request by nemo794**
This pull request updates the installation process and fixes issues with the setup.py script. The setup.py script can now be used in either `install` mode or in `develop` mode.

Changes include: Removed extraneous files. Revised setup.py. Updated README.md. Modified scripts for the the Docker image to reflect the correct version labeling per the SAS User Guide.

Before approving this Pull Request, please test to ensure that this works:
1) Create a new (clean) conda environment
2) Follow all of the instructions in the README.md (including creating a new clone of the repo) to make sure that it works.
3) Please also check that the Docker Image can still be built and run from the command line, per the SAS User Guide.

Thank you!

### CODE REVIEW

**Review by gshiroma — COMMENTED** [review]
Thank you so much for these updates, @nemo794 ! All changes look great! I'll find some time to test them soon.

**Review by gshiroma — APPROVED** [review]
Thank you so much for this PR, @nemo794 ! It works like a charm!

**Review by hfattahi — APPROVED** [review]
LGTM. It would be good to have instruction to install the latest released version and to install the developer branch. Also we should build the conda package for this software soon. But for now it looks good to me.

**Comment by gshiroma** [comment]
Thank you, @hfattahi !

**Comment by nemo794** [comment]
Thank you @hfattahi !

**Pull request merged**
